### ISSUE TITLE
Buy the firmware 

### ISSUE THREAD

**Issue by vincyrei** [h-RAT/Willy_Firmware_CC1101_ESP32_Display_Touchscreen#1]
good morning, I don't know what happened, but I'm very sorry.  you do a great job and I admire you for that.  is it possible to buy your own firmware?  how can I do?

maybe I didn't explain myself...I'm not the author of the firmware...even I'm asking its creator to be able to buy the firmware.

**Comment by cyfroniasty** [comment]
I would need software for your project?? in return I can give you for my
projects

wt., 8 sie 2023 o 07:16 vincyrei ***@***.***> napisał(a):

**Comment by cyfroniasty** [comment]
what is the price of the software??

wt., 8 sie 2023 o 08:58 cyfronik cyfronowy ***@***.***>
napisał(a):

**Comment by vincyrei** [comment]
adarkangel@hotmail.it

**Comment by h-RAT** [comment]
Add me on discord for more info.

 Discord: h-RAT#2465
