### ISSUE TITLE
IR Transceiver

### ISSUE THREAD

**Issue by Mysteriza** [h-RAT/Willy_Firmware_CC1101_ESP32_Display_Touchscreen#3]
Is it possible to add IR transmitter and receiver to this project? If this were possible, I would probably buy it!

And I'm also making a project similar to yours, it's just that I can't use sub-ghz yet, and I can't use a memory card, because I'm using RFID reader module, so not enough pins.

**Comment by h-RAT** [comment]
Hi, no IR transmitter planned for the moment.
